### ISSUE TITLE
Dikastis fora do ar

### ISSUE THREAD

**Issue by srmq** [danbsts/dikastis-issues#1]
Neste momento, 15/07/2024, 18h18, o dikastis está fora do ar.
![Captura de tela_15-7-2024_181949_www dikastis com br](https://github.com/user-attachments/assets/0b8e4212-b518-4c98-b015-229e00f03f4a)

**Comment by danbsts** [comment]
Olá Sergio!

Esse problema ocorreu devido a uma falha nos servidores do CIn, mas já foi reestabelecido! Obrigado por reportá-lo 😄
